### PR TITLE
First batch of tests.

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR adds some tests and fixes the conda packaging issue.

@rhattersley Not sure who I should ping to ask for a review.

PS: I will add the remaining tests in another PR.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Almost there.  Need to fix the `site.cfg` (also need for MacOS conda package.)

**Comment by ocefpaf** [comment]
I think this PR fixes the tests and possibly the conda package as well.  (It took me a while to understand how ctypes `find_library` and how to use the `site.cfg` to specify a search directory for the library.)

@rhattersley Not sure who I should ping to ask for a review.

PS: I will add the rest of the tests in another PR.

**Comment by pelson** [comment]
:+1: - progress! Thanks @ocefpaf. What I didn't do in this review is check that the tests you've put in, are equivalent to those in Iris. Would you mind commenting how much effort was taken to change from iris tests -> cf_units tests? Was it a simple copy & paste, or was there work needed throughout?

**Comment by ocefpaf** [comment]
Yes, I am copying and pasting the same tests from iris.  The only significant difference is that I do not use the class `tests.IrisTest`.  It seems that cf_units is fine with just `unittest.TestCase`.   (At least for now, there are more tests coming in future PRs.) 

Here is the full diff:

https://gist.github.com/ocefpaf/e9cfb9f3a9d443c877d6

It is mostly renaming and  pep8 fixes.

**Pull request merged**
