### PR TITLE
Added the coveralls badge.

### PR DESCRIPTION
**Pull request by bjlittle**
Requires #58

### CODE REVIEW

**Comment by DPeterK** [comment]
Great!

**Comment by DPeterK** [comment]
Whoa, not so great... These aren't rendering properly :hankey:

**Comment by bjlittle** [comment]
Dah! I'll fix it ...

**Comment by DPeterK** [comment]
@bjlittle might be because cf_units' readme is an `RST` file rather than an `MD` file...

**Comment by bjlittle** [comment]
Guilty as charged :blush:

**Pull request merged**
