### PR TITLE
Proposal to update cf_units tests

### PR DESCRIPTION
**Pull request by DPeterK**
This PR contains a subset (~50%) of the first round of changes to bring `cf_units.tests.test_unit` more in line with current testing practices. This involves:
- renaming test classes and methods,
- making use of different `assert...` methods, notably `assertRaisesRegexp`,
- using `with` blocks in conjunction with the previous,
- re-ordering some tests, _but_
- **not** regularly make judgement calls on the ascribed _value_ of test methods, i.e. whether the functionality tested is worth testing.

The plan with this PR is that it is the first step in a longer goal of removing the `cf_units.tests.test_unit` module entirely by adding the updated tests from this module as appropriate into `cf_units.tests.unit.Unit.test_Unit`.

If the general approach demonstrated by this PR is approved then I will continue to tidy up the rest of the tests in this module, either as additional commits to this PR or in a follow-up PR, and then move on with the process by merging these tests into the other test module referenced above.

Note: these changes were originally targetted at `iris.tests.test_unit`, but a conversation with @marqh pointed me in the direction of suggesting the changes here rather than on the Iris repo.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks for sending this here.  It avoids duplicate efforts like #33. Ideally we should fold `cf_untis` back into iris by making it a dependency.

The travis failure has nothing to due with the PR.  I am fixing that now.

**Comment by ocefpaf** [comment]
Travis is fixed in https://github.com/SciTools/cf_units/pull/35.

**Comment by DPeterK** [comment]
Thanks for the heads-up @ocefpaf; it was actually my [Iris #1813](https://github.com/SciTools/iris/pull/1813) that originally prompted this work! It would be nice to avoid the duplicated effort...

**Comment by DPeterK** [comment]
I've rebased now that #35 has been merged.

**Comment by ocefpaf** [comment]
Maybe we should merge/reject #33  before merging this one.

**Comment by DPeterK** [comment]
> Maybe we should merge/reject #33 before merging this one.

Or the other way round, I've already rebased this PR once today :wink:

**Comment by ocefpaf** [comment]
> Or the other way round, I've already rebased this PR once today

OK.  You win :smile: 

Merging this.

**Pull request merged**
