### PR TITLE
3p0px update

### PR DESCRIPTION
**Pull request by bjlittle**
### Description
Update the `v3.0.x` release feature branch with updates from `main`.

Note that, the merge-back from `v3.0.x` to `main` (#192) was squash merged rather than done with a merge commit, therefore the `v3.0.x` commit `5aa890a` has been re-hashed as `d9f280c` - I'm not going to bother unpicking this.

### CODE REVIEW

**Comment by bjlittle** [comment]
@ocefpaf Fancy taking this on?

Please ensure to do a **merge commit**, rather than a **squash commit** 👍

This'll update the `v3.0.x` release feature branch, at which point I'll cut a post patch release and we can see whether the GH PyPI publish action is behaving :+1:

**Comment by ocefpaf** [comment]
Sure.

> Please ensure to do a **merge commit**, rather than a **squash commit** 

Oh. I thought you set that up and liked it that way, I really dislike it.
 
> This'll update the `v3.0.x` release feature branch, at which point I'll cut a post patch release and we can see whether the GH PyPI publish action is behaving

:+1:

**Review by ocefpaf — APPROVED** [review]

**Comment by bjlittle** [comment]
@ocefpaf okay, so I'm testing the GH action after seeing initial failures.

I'm at the point where the wheels successfully build. However, installing the wheels for the appropriate python versions and running the tests results in some failures.... Which I'm investigating 🤔

**Comment by ocefpaf** [comment]
I can take a look later next week. We needed one GHA merged to get it to work, now it is easier to debug.

**Comment by bjlittle** [comment]
@ocefpaf I've finally got it working!

There were a few hoops to jump through, and I think that I've finally settled on a reasonable GHA workflow, see https://github.com/bjlittle/cf-units/actions/runs/1086268122

I also had to make a couple of changes to `cf-units`, but nothing major. However, the biggest gotcha that stumped me was working out that the `manylinux2010` is too old a platform to build the `cf-units` wheels on as the `yum install -y udunits2-devel` installed `udunits2 2.1.19-1`... which is ~10 years old and causes some serious parsing errors in `cf-units` that the test suite was catching - and I couldn't work around them :cry: 

However, I've re-built the wheels based on `manylinux2014` (see [here](https://github.com/pypa/manylinux#manylinux) for the differences), which in turn installs `udunits2 2.2.20-2` circa 2015, and that's modern enough to successfully build `py37`, `py38` and `py39` with all the tests passing :partying_face: 

I'll push a PR to SciTools/cf-units today or tomorrow. BTW it also includes the `sdist`.

If you're interested my branch is https://github.com/bjlittle/cf-units/tree/test-action and I was testing with this release https://github.com/bjlittle/cf-units/releases/tag/v3.0.1.post0

I may now extend to cover `macos`, but I'll see how I'm doing for time

**Pull request merged**
