### PR TITLE
Test on python 3.7...

### PR DESCRIPTION
**Pull request by ocefpaf**
... and fix the test.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@bjlittle or @pelson can you take a look at this PR? I kind of have use for this in CIs downstream...

**Comment by lbdreyer** [comment]
@ocefpaf thanks for this! I was just about to look into adding python 3.7 but found you had already done it!

**Comment by ocefpaf** [comment]
If you agree I can put together a new release with the Python 3.7 support.

**Comment by lbdreyer** [comment]
@ocefpaf I think that's  a good idea :+1: 

Then it will make it easier to update all the packages that depend on cf-units to include Python 3.7 testing

**Comment by ocefpaf** [comment]
@lbdreyer actually I was mistaken and only a test needed fixing. (For some reason I thought that I also modified the core code base.)

So no new releases is actually needed to run this on Python 3.7. We can wait for more functional changes to do that.

**Pull request merged**
