### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by DPeterK**
Given the [comment](https://github.com/SciTools/cf_units/pull/36#issuecomment-153313070) and follow-on discussion on #36, I think it is now time for a new release of `cf_units`.

What do people think? Bump version to v0.2 as proposed here, or go as far as v0.5? Thoughts welcome.

### CODE REVIEW

**Comment by ajdawson** [comment]
I doubt v0.5 has special meaning attached to it as far as most are concerned so if you want a zero-point version you may as well stick with numerical order.

**Comment by rhattersley** [comment]
I'd suggest either 0.2 or 1.0. If there's nothing outstanding and assuming it really is a "drop in replacement for iris.units" then perhaps it's mature enough for 1.0?

**Comment by rhattersley** [comment]
(Is there an agreed version scheme for this package yet? e.g. [PEP 440 + SemVer](https://www.python.org/dev/peps/pep-0440/#semantic-versioning))

**Comment by DPeterK** [comment]
Thanks for that outlook @ajdawson!

@rhattersley the plan is that cf_units is now at the point of being that drop-in replacement for `iris.unit` and I know that @marqh is looking at this version bump from this perspective. So perhaps this does indeed become the v1.0 bump!

**Comment by pelson** [comment]
How progressive do we want to be? I've been using versioneer pretty heavily on Win/OSX/Linux for a while now, and this would be the perfect place to start introducing it into scitools. On the downside, it is using a versioneer that hasn't yet been merged onto master (and honestly, I haven't seen much progress on that happening anytime soon).

**Comment by rhattersley** [comment]
My 2p: :+1: for using something like versioneer, but :-1: if it's not even on master (let alone released). (Is there anything we can do to help nudge versioneer along?)

**Comment by pelson** [comment]
> Is there anything we can do to help nudge versioneer along?

I'll nudge shortly. :wink:

**Comment by marqh** [comment]
:+1: for v1.0

**Comment by DPeterK** [comment]
In light of comments above, I've added a commit that changes the version string to `1.0.0`. I've also changed the name of this PR to reflect this change in version.

I figure that for getting things moving on this and the associated changes in Iris, we be bold and state that this is v1.0 (and Iris) ready. We can always add in versioneer at a later date; it seems a shame to hold this up while waiting for that...

**Comment by pelson** [comment]
@ocefpaf - would you do the honours?

**Comment by ocefpaf** [comment]
Thanks!

**Pull request merged**
