### PR TITLE
Implement Unit.change_calendar

### PR DESCRIPTION
**Pull request by rcomer**
### Description

Inspired by https://github.com/SciTools/cf-units/issues/185#issuecomment-1051031393, introduce a method to replace a unit's calendar (if original and new calendar both represent the real world).  I think this should be a step towards solving #185, and also may be useful for UM users if https://github.com/SciTools/iris/issues/3561 is implemented.

@larsbarring I'd appreciate any feedback you may have on this.

### CODE REVIEW

**Comment by rcomer** [comment]
I don't think the test failures are due to my change....

**Comment by trexfeathers** [comment]
> I don't think the test failures are due to my change....

@bjlittle and I are working on it

**Comment by trexfeathers** [comment]
@rcomer could you update your branch from `main`?

**Comment by trexfeathers** [comment]
Also this looks good to me and we're hoping to cut a release soon, so @larsbarring if you do have any thoughts, now is the time 😊

**Comment by rcomer** [comment]
Thanks @trexfeathers, tests all passing now 🙂

**Review by trexfeathers — APPROVED** [review]

**Pull request merged**
