### PR TITLE
Catch up with iris PR 1813

### PR DESCRIPTION
**Pull request by ocefpaf**
There is some noise, but this PR essentially adds the modifications needed to run the `unit/test_Unit.py` and implements the modifications from https://github.com/SciTools/iris/pull/1813.

### CODE REVIEW

**Comment by ocefpaf** [comment]
I was testing this with a newer version of pep8.  I guess that the files are OK for `pep8=1.5.7`

**Comment by DPeterK** [comment]
FWIW I'd prefer to see the `six` changes kept separate to the changes that catch `cf_units` up with Iris after the merge of Iris#1813... but I'm not going to let this stand in the way of progress unnecessarily.

**Comment by marqh** [comment]
Hello @ocefpaf 

I had not realise you were in the process of updating here.

I have raised a PR which is inconsistent with this one:
#36 
this alters the module structure, as when I tried to use the **init** with its cunning imports with Iris lots of things did not work

In order to encourage discussion I put up a change which moved this structure.

In making the tests pass I also pulled in the code alteration from iris 1813

So, these two PRs are now in conflict; I'm sorry about this.  When I prepared my PR yesterday this one was not up

Please may we discuss the relative merits of these two different approaches and agree which route we would like to take?

thank you
mark

**Comment by ocefpaf** [comment]
Right now it is probably easier to merge #36 and #34 and then re-do #33.

> In making the tests pass I also pulled in the code alteration from iris 1813

I don't see the changes from [iris 1813](https://github.com/SciTools/iris/pull/1813) in #36.  But that is not a problem.  By re-doing #33 I can make it cleaner and keep the `six`, and some other changes, separate.

**Comment by DPeterK** [comment]
> I don't see the changes 

What @marqh has done is include the code change to `Unit.convert` that makes convert independent of endianness; the tests I also added in [Iris #1813](https://github.com/SciTools/iris/pull/1813) have not also been added here. Given all the other things that are changing here at the moment I'm not too worried by this!

**Comment by DPeterK** [comment]
> By re-doing #33 I can make it cleaner and keep the six, and some other changes, separate

:+1: for this approach!

**Comment by ocefpaf** [comment]
Closed in favor of #34 and #33.  The changes here will be in a new PR further down the road.

**Pull request closed without merging**
