### PR TITLE
PyPI classifiers and ReST README.txt

### PR DESCRIPTION
**Pull request by ocefpaf**
Added some PyPI classifiers and README.txt (ReST format).

### CODE REVIEW

**Comment by rhattersley** [comment]
If you rename `README.txt` to `README.rst` you can get rid of `README.md` completely. (GitHub will show `README.rst` instead.)

**Comment by ocefpaf** [comment]
Did not know that GitHub was `README.rst` friendly.  I just made the change.  Thanks!

**Comment by ocefpaf** [comment]
Added an extra commit to fix #29

**Comment by rhattersley** [comment]
Looks good to me. :+1:

**Pull request merged**
